# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadSourceConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("indiamart", "IndiaMART"),
                            ("meta_facebook", "Meta - Facebook Lead Ads"),
                            ("meta_instagram", "Meta - Instagram Lead Ads"),
                            ("99acres", "99acres"),
                            ("housing_com", "Housing.com"),
                            ("magicbricks", "MagicBricks"),
                            ("justdial", "JustDial"),
                            ("sulekha", "Sulekha"),
                            ("tradeindia", "TradeIndia"),
                            ("google_ads", "Google Ads Lead Forms"),
                            ("website", "Website Widget"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual Entry"),
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("whatsapp", "WhatsApp Inbound"),
                            ("referral", "Referral"),
                        ],
                        db_index=True,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error — check credentials"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("credentials", models.JSONField(blank=True, default=dict)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Source-specific options: auto_assign_to agent_id, default_priority, duplicate_action, etc.",
                    ),
                ),
                (
                    "webhook_token",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Auto-generated token for the inbound webhook URL.",
                        max_length=64,
                    ),
                ),
                ("total_leads_received", models.PositiveIntegerField(default=0)),
                ("last_received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "verbose_name": "Lead Source Config",
                "verbose_name_plural": "Lead Source Configs",
                "ordering": ["source"],
            },
        ),
        migrations.CreateModel(
            name="WebhookLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("indiamart", "IndiaMART"),
                            ("meta_facebook", "Meta - Facebook Lead Ads"),
                            ("meta_instagram", "Meta - Instagram Lead Ads"),
                            ("99acres", "99acres"),
                            ("housing_com", "Housing.com"),
                            ("magicbricks", "MagicBricks"),
                            ("justdial", "JustDial"),
                            ("sulekha", "Sulekha"),
                            ("tradeindia", "TradeIndia"),
                            ("google_ads", "Google Ads Lead Forms"),
                            ("website", "Website Widget"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual Entry"),
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("whatsapp", "WhatsApp Inbound"),
                            ("referral", "Referral"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("method", models.CharField(default="POST", max_length=10)),
                ("headers", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("processed", models.BooleanField(db_index=True, default=False)),
                ("leads_created", models.PositiveSmallIntegerField(default=0)),
                ("leads_updated", models.PositiveSmallIntegerField(default=0)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                (
                    "config",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_logs",
                        to="integrations.leadsourceconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Log",
                "verbose_name_plural": "Webhook Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "processed", "created_at"],
                        name="integration_source_bfaf24_idx",
                    )
                ],
            },
        ),
    ]
