# Generated by Django 5.1.4 on 2026-09-04 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("leads", "0004_alter_lead_source_alter_leadimportjob_default_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsourceconfig",
            name="source",
            field=models.CharField(
                choices=[
                    ("indiamart", "IndiaMART"),
                    ("meta_facebook", "Meta - Facebook Lead Ads"),
                    ("meta_instagram", "Meta - Instagram Lead Ads"),
                    ("meta_ctwa", "Meta - Click to WhatsApp"),
                    ("99acres", "99acres"),
                    ("housing_com", "Housing.com"),
                    ("magicbricks", "MagicBricks"),
                    ("justdial", "JustDial"),
                    ("sulekha", "Sulekha"),
                    ("tradeindia", "TradeIndia"),
                    ("google_ads", "Google Ads Lead Forms"),
                    ("website", "Website Widget"),
                    ("webhook", "Webhook"),
                    ("manual", "Manual Entry"),
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                    ("whatsapp", "WhatsApp Inbound"),
                    ("referral", "Referral"),
                ],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="webhooklog",
            name="source",
            field=models.CharField(
                choices=[
                    ("indiamart", "IndiaMART"),
                    ("meta_facebook", "Meta - Facebook Lead Ads"),
                    ("meta_instagram", "Meta - Instagram Lead Ads"),
                    ("meta_ctwa", "Meta - Click to WhatsApp"),
                    ("99acres", "99acres"),
                    ("housing_com", "Housing.com"),
                    ("magicbricks", "MagicBricks"),
                    ("justdial", "JustDial"),
                    ("sulekha", "Sulekha"),
                    ("tradeindia", "TradeIndia"),
                    ("google_ads", "Google Ads Lead Forms"),
                    ("website", "Website Widget"),
                    ("webhook", "Webhook"),
                    ("manual", "Manual Entry"),
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                    ("whatsapp", "WhatsApp Inbound"),
                    ("referral", "Referral"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MetaWhatsAppEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(
                        help_text="Stable per-event key, e.g. 'msg:wamid.ABC' or 'status:wamid.ABC:read'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Meta's wamid for the message this event concerns.",
                        max_length=200,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("message", "Inbound message"),
                            ("status", "Delivery status"),
                        ],
                        default="message",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("ignored", "Ignored (unsupported event)"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("conversation_id", models.UUIDField(blank=True, null=True)),
                ("created_lead", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, default="", max_length=500)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meta_whatsapp_events",
                        to="leads.lead",
                    ),
                ),
                (
                    "webhook_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_events",
                        to="integrations.webhooklog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta WhatsApp Event",
                "verbose_name_plural": "Meta WhatsApp Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="integration_status_dceaa9_idx",
                    )
                ],
            },
        ),
    ]
