# Generated by Django 5.1.4 on 2026-09-08 13:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_agent_role_back_office'),
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_terminal', models.BooleanField(default=False, help_text='Nobody moves out of a terminal stage (Hired, Rejected).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('on_hold', 'On Hold')], db_index=True, default='active', max_length=15)),
                ('applied_on', models.DateField(default=django.utils.timezone.localdate)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text="Recruiter's own 1-5 rating.", null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=300)),
                ('stage_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, help_text='The recruiter driving this application.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_applications', to='authentication.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('stage_change', 'Stage Change'), ('status_change', 'Status Change'), ('note', 'Note'), ('interview', 'Interview'), ('feedback', 'Feedback'), ('offer', 'Offer')], max_length=20)),
                ('summary', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authentication.agent')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='recruitment.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('source', models.CharField(choices=[('referral', 'Referral'), ('job_board', 'Job Board (Naukri/Indeed)'), ('linkedin', 'LinkedIn'), ('careers_page', 'Careers Page'), ('agency', 'Recruitment Agency'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='other', max_length=20)),
                ('current_company', models.CharField(blank=True, default='', max_length=150)),
                ('current_designation', models.CharField(blank=True, default='', max_length=150)),
                ('total_experience_years', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notice_period_days', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('skills', models.JSONField(blank=True, default=list, help_text='List of skill strings.')),
                ('resume', models.FileField(blank=True, null=True, upload_to='recruitment/resumes/')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_candidates', to='authentication.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, default='', help_text='e.g. Technical Round 1', max_length=120)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=45)),
                ('mode', models.CharField(choices=[('phone', 'Phone'), ('video', 'Video'), ('onsite', 'On-site')], default='video', max_length=10)),
                ('location_or_link', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='scheduled', max_length=15)),
                ('notes', models.TextField(blank=True, default='')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews', to='authentication.agent')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.CharField(choices=[('strong_no', 'Strong No'), ('no', 'No'), ('maybe', 'Maybe'), ('yes', 'Yes'), ('strong_yes', 'Strong Yes')], max_length=15)),
                ('scores', models.JSONField(blank=True, default=dict, help_text='Per-criterion scores, e.g. {"communication": 4, "technical": 3}.')),
                ('strengths', models.TextField(blank=True, default='')),
                ('concerns', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recruitment.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedback', to='authentication.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, help_text='Short reference, e.g. ENG-2026-04.', max_length=30, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('openings', models.PositiveIntegerField(default=1, help_text='How many people are being hired for this role.')),
                ('min_experience_years', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('max_experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True, default='', help_text='Job description.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('on_hold', 'On Hold'), ('closed', 'Closed')], db_index=True, default='draft', max_length=15)),
                ('opened_on', models.DateField(blank=True, null=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('hiring_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_openings', to='authentication.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='opening',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobopening'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fixed_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('variable_component', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('joining_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('joining_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='recruitment/offers/')),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], db_index=True, default='draft', max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='recruitment.application')),
                ('converted_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_offer', to='hrms.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='authentication.agent')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hrms.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='recruitment.pipelinestage'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['email', 'phone'], name='ats_cand_contact_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status', 'scheduled_at'], name='ats_int_status_time_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewfeedback',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AddIndex(
            model_name='jobopening',
            index=models.Index(fields=['status', 'department'], name='ats_open_status_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['opening', 'status'], name='ats_app_open_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'opening')},
        ),
    ]
