# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("marketing", "Marketing"),
                            ("utility", "Utility / Transactional"),
                            ("authentication", "Authentication (OTP)"),
                        ],
                        default="marketing",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="e.g. en, hi, mr", max_length=10
                    ),
                ),
                (
                    "header_text",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "body_text",
                    models.TextField(help_text="Use {{1}}, {{2}} for variables."),
                ),
                (
                    "footer_text",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "variable_mapping",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Map {{N}} to Lead fields. e.g. {"1": "name", "2": "city"}',
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wati", "WATI"),
                            ("interakt", "Interakt"),
                            ("gupshup", "Gupshup"),
                            ("aisensy", "AiSensy"),
                            ("twilio", "Twilio"),
                            ("meta_cloud", "Meta Cloud API (Direct)"),
                            ("360dialog", "360dialog"),
                        ],
                        default="interakt",
                        max_length=30,
                    ),
                ),
                (
                    "provider_template_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paused", "Paused by Meta"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "WhatsApp Template",
                "verbose_name_plural": "WhatsApp Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BulkCampaign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "audience_filters",
                    models.JSONField(
                        default=dict,
                        help_text='Filter criteria: {"status": "interested", "city": "Mumbai"}',
                    ),
                ),
                ("estimated_recipients", models.PositiveIntegerField(default=0)),
                (
                    "email_subject",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("email_body", models.TextField(blank=True, default="")),
                (
                    "sms_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Max 160 chars for single SMS.",
                        max_length=160,
                    ),
                ),
                (
                    "sms_sender_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="TRAI-approved 6-char sender ID.",
                        max_length=11,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("delivered_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("replied_count", models.PositiveIntegerField(default=0)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to="authentication.agent",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="communications.whatsapptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Campaign",
                "verbose_name_plural": "Bulk Campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=300)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. mailgun, sendgrid, ses",
                        max_length=30,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="communications.bulkcampaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="leads.lead",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Log",
                "verbose_name_plural": "Email Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("message", models.CharField(max_length=1600)),
                ("sender_id", models.CharField(blank=True, default="", max_length=11)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("dnd_blocked", "Blocked (DND)"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. msg91, textlocal, fast2sms",
                        max_length=30,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("cost_paise", models.PositiveIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sms_messages",
                        to="communications.bulkcampaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_messages",
                        to="leads.lead",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Log",
                "verbose_name_plural": "SMS Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped (DND/Invalid)"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="communications.bulkcampaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_recipients",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Campaign Recipient",
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="communicati_campaig_d3e261_idx",
                    )
                ],
                "unique_together": {("campaign", "lead")},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppMessage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("outbound", "Outbound"), ("inbound", "Inbound")],
                        db_index=True,
                        default="outbound",
                        max_length=10,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("template", "Template"),
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wati", "WATI"),
                            ("interakt", "Interakt"),
                            ("gupshup", "Gupshup"),
                            ("aisensy", "AiSensy"),
                            ("twilio", "Twilio"),
                            ("meta_cloud", "Meta Cloud API (Direct)"),
                            ("360dialog", "360dialog"),
                        ],
                        default="interakt",
                        max_length=30,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("received", "Received"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("media_url", models.URLField(blank=True, default="")),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_messages",
                        to="communications.bulkcampaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_messages",
                        to="leads.lead",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for inbound messages or bulk sends.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="whatsapp_sent",
                        to="authentication.agent",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template used (for outbound template messages).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="communications.whatsapptemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Message",
                "verbose_name_plural": "WhatsApp Messages",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lead", "created_at"],
                        name="communicati_lead_id_a0af51_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="communicati_status_43397a_idx",
                    ),
                ],
            },
        ),
    ]
