# Generated by Django 5.1.4 on 2026-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsapptemplate",
            name="header_media_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Image/video/document URL for a media header (e.g. Cloudinary).",
                max_length=600,
            ),
        ),
        migrations.AddField(
            model_name="whatsapptemplate",
            name="header_type",
            field=models.CharField(
                choices=[
                    ("none", "No header"),
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("document", "Document"),
                ],
                default="none",
                help_text="WhatsApp template header type. 'image' shows a banner image.",
                max_length=12,
            ),
        ),
    ]
