# Generated by Django 6.0.6 on 2026-07-10 17:28

import apps.core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0002_whatsapptemplate_header_media_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "singleton",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wati", "WATI"),
                            ("interakt", "Interakt"),
                            ("gupshup", "Gupshup"),
                            ("aisensy", "AiSensy"),
                            ("twilio", "Twilio"),
                            ("meta_cloud", "Meta Cloud API (Direct)"),
                            ("360dialog", "360dialog"),
                        ],
                        default="interakt",
                        help_text="Which WhatsApp Business API the tenant sends through.",
                        max_length=30,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Off until credentials are verified. Sends fall back to a no-op while off.",
                    ),
                ),
                (
                    "credentials",
                    apps.core.crypto.EncryptedJSONField(blank=True, default=dict),
                ),
                ("default_language", models.CharField(default="en", max_length=10)),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Configuration",
                "verbose_name_plural": "WhatsApp Configuration",
            },
        ),
    ]
