# Generated by Django 5.1.4 on 2026-09-04 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_agentstatus_agentstatuslog"),
        ("communications", "0003_whatsappconfig"),
        ("leads", "0004_alter_lead_source_alter_leadimportjob_default_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconfig",
            name="create_leads_from_inbound",
            field=models.BooleanField(
                default=True,
                help_text="Create a CRM lead when an unknown number messages in.",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="ctwa_leads_only",
            field=models.BooleanField(
                default=False,
                help_text="Only open leads for conversations carrying Click-to-WhatsApp ad attribution. Organic inbound is still logged against an existing lead, but does not create a new one.",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="graph_api_version",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override the platform Graph API version, e.g. v26.0. Blank = platform default.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="inbound_assign_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent new inbound leads are assigned to. Unset = unassigned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inbound_whatsapp_leads",
                to="authentication.agent",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="inbound_enabled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Accept inbound WhatsApp webhooks from Meta for this tenant.",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="last_webhook_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When Meta last delivered any webhook to this tenant.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="last_webhook_error",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="reopen_lead_on_inbound",
            field=models.BooleanField(
                default=True,
                help_text="When a closed/lost lead messages again, move it back to New so it resurfaces in the queue instead of staying buried.",
            ),
        ),
        migrations.AddField(
            model_name="whatsappconfig",
            name="total_inbound_messages",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Media ids/mime types, reply context, and the normalized inbound envelope. No credentials are ever stored here.",
            ),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="wa_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Meta's own message timestamp — authoritative ordering, which created_at (our receive time) is not.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("template", "Template"),
                    ("image", "Image"),
                    ("document", "Document"),
                    ("audio", "Audio"),
                    ("video", "Video"),
                    ("sticker", "Sticker"),
                    ("location", "Location"),
                    ("contacts", "Contact card"),
                    ("button", "Button reply"),
                    ("interactive", "Interactive reply"),
                    ("reaction", "Reaction"),
                    ("order", "Order"),
                    ("system", "System"),
                    ("unsupported", "Unsupported"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="WhatsAppConversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "contact_wa_id",
                    models.CharField(
                        db_index=True,
                        help_text="Customer's WhatsApp ID exactly as Meta sends it (digits, no +).",
                        max_length=25,
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Normalized E.164 form of contact_wa_id.",
                        max_length=15,
                    ),
                ),
                (
                    "whatsapp_profile_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Display name from the customer's WhatsApp profile.",
                        max_length=200,
                    ),
                ),
                (
                    "business_phone_number_id",
                    models.CharField(
                        db_index=True,
                        help_text="Meta phone_number_id the message was delivered to.",
                        max_length=50,
                    ),
                ),
                (
                    "business_display_phone",
                    models.CharField(blank=True, default="", max_length=25),
                ),
                (
                    "whatsapp_business_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="WABA id (webhook entry.id).",
                        max_length=50,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("wati", "WATI"),
                            ("interakt", "Interakt"),
                            ("gupshup", "Gupshup"),
                            ("aisensy", "AiSensy"),
                            ("twilio", "Twilio"),
                            ("meta_cloud", "Meta Cloud API (Direct)"),
                            ("360dialog", "360dialog"),
                        ],
                        default="meta_cloud",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("first_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_message_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("is_ad_referred", models.BooleanField(db_index=True, default=False)),
                (
                    "referral_source_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Meta referral.source_type — "ad" or "post".',
                        max_length=20,
                    ),
                ),
                (
                    "referral_source_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Meta referral.source_id — the ad id (or post id).",
                        max_length=100,
                    ),
                ),
                (
                    "referral_source_url",
                    models.URLField(blank=True, default="", max_length=800),
                ),
                (
                    "referral_headline",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("referral_body", models.TextField(blank=True, default="")),
                (
                    "referral_media_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "ctwa_clid",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Click-to-WhatsApp click id, for Conversions API attribution.",
                        max_length=512,
                    ),
                ),
                (
                    "meta_ad_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "meta_ad_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "meta_adset_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "meta_adset_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "meta_campaign_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "meta_campaign_name",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "attribution_enriched_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "attribution_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("referral_payload", models.JSONField(blank=True, default=dict)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whatsapp_conversations",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "WhatsApp Conversation",
                "verbose_name_plural": "WhatsApp Conversations",
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="communications.whatsappconversation",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappmessage",
            index=models.Index(
                fields=["conversation", "wa_timestamp"],
                name="communicati_convers_269921_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["lead", "status"], name="communicati_lead_id_1ac1b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="whatsappconversation",
            index=models.Index(
                fields=["is_ad_referred", "created_at"],
                name="communicati_is_ad_r_dcdd55_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="whatsappconversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "open")),
                fields=("contact_wa_id", "business_phone_number_id"),
                name="uniq_open_wa_conversation_per_contact",
            ),
        ),
    ]
