# Generated by Django 5.1.4 on 2026-09-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0004_whatsappconfig_create_leads_from_inbound_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkcampaign",
            name="failure_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
