# Generated by Django 5.1.4 on 2026-09-27 08:39

from django.db import migrations, models


def give_existing_configs_a_token(apps, schema_editor):
    import secrets

    WhatsAppConfig = apps.get_model("communications", "WhatsAppConfig")
    for config in WhatsAppConfig.objects.filter(webhook_token=""):
        config.webhook_token = secrets.token_urlsafe(32)
        config.save(update_fields=["webhook_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("communications", "0005_bulkcampaign_failure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconfig",
            name="webhook_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.RunPython(give_existing_configs_a_token, migrations.RunPython.noop),
    ]
