# Generated by Django 5.1.4 on 2026-10-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_canonical_state_codes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerinvoiceitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="erp.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("nos", "Nos"),
                    ("pcs", "Pieces"),
                    ("box", "Box"),
                    ("set", "Set"),
                    ("pack", "Pack"),
                    ("dozen", "Dozen"),
                    ("pair", "Pair"),
                    ("hour", "Hour"),
                    ("day", "Day"),
                    ("month", "Month"),
                    ("year", "Year"),
                    ("job", "Job"),
                    ("kg", "Kg"),
                    ("gram", "Gram"),
                    ("ton", "Tonne"),
                    ("litre", "Litre"),
                    ("ml", "ml"),
                    ("meter", "Meter"),
                    ("sqft", "Sq. ft"),
                    ("sqm", "Sq. m"),
                ],
                default="nos",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="quotationitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="erp.product",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderitem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="erp.product",
            ),
        ),
    ]
