# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Label shown in the form.", max_length=100
                    ),
                ),
                (
                    "field_key",
                    models.SlugField(
                        help_text="Internal key used in API. Auto-generated from name.",
                        unique=True,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short Text"),
                            ("textarea", "Long Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("dropdown", "Dropdown"),
                            ("checkbox", "Checkbox (Yes/No)"),
                            ("phone", "Phone Number"),
                            ("url", "URL"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='For dropdown fields: ["Option A", "Option B"]',
                    ),
                ),
                (
                    "placeholder",
                    models.CharField(blank=True, default="", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Custom Field",
                "verbose_name_plural": "Custom Fields",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.BigIntegerField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "phone",
                    models.CharField(
                        db_index=True,
                        help_text="Primary contact. +91XXXXXXXXXX format stored internally.",
                        max_length=15,
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, default="", max_length=254
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("pincode", models.CharField(blank=True, default="", max_length=6)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("indiamart", "IndiaMART"),
                            ("meta_facebook", "Meta - Facebook Lead Ads"),
                            ("meta_instagram", "Meta - Instagram Lead Ads"),
                            ("99acres", "99acres"),
                            ("housing_com", "Housing.com"),
                            ("magicbricks", "MagicBricks"),
                            ("justdial", "JustDial"),
                            ("sulekha", "Sulekha"),
                            ("tradeindia", "TradeIndia"),
                            ("google_ads", "Google Ads Lead Forms"),
                            ("website", "Website Widget"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual Entry"),
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("whatsapp", "WhatsApp Inbound"),
                            ("referral", "Referral"),
                        ],
                        db_index=True,
                        default="manual",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("attempted", "Attempted"),
                            ("contacted", "Contacted"),
                            ("interested", "Interested"),
                            ("not_interested", "Not Interested"),
                            ("follow_up", "Follow-up Scheduled"),
                            ("negotiation", "In Negotiation"),
                            ("converted", "Converted / Won"),
                            ("lost", "Lost"),
                            ("duplicate", "Duplicate"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("hot", "Hot 🔥"),
                            ("warm", "Warm 🌤"),
                            ("cold", "Cold ❄️"),
                        ],
                        db_index=True,
                        default="warm",
                        max_length=10,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget in INR (e.g., property budget for real estate).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "requirement",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="What the lead is looking for (BHK type, location, etc.).",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Lead quality score 0-100 (auto-calculated or manual).",
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline_stage",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Visual kanban column position (1=leftmost/new, 10=won/lost).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                (
                    "deal_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected deal value in INR.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "source_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw data from the lead source (webhook payload, ad data, etc.).",
                    ),
                ),
                (
                    "source_lead_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="External lead ID from the source platform.",
                        max_length=200,
                    ),
                ),
                (
                    "next_followup_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Next scheduled follow-up datetime (denormalized for fast querying).",
                        null=True,
                    ),
                ),
                ("last_contacted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of contact attempts (calls + messages).",
                    ),
                ),
                (
                    "is_dnd",
                    models.BooleanField(
                        default=False,
                        help_text="True if number is in TRAI Do-Not-Disturb registry.",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of tag strings. E.g. ["premium", "referral", "hot"]',
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_leads",
                        to="authentication.agent",
                    ),
                ),
                (
                    "territory_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="territory_leads",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("status_change", "Status Change"),
                            ("assigned", "Assigned"),
                            ("note_added", "Note Added"),
                            ("followup_created", "Follow-up Created"),
                            ("followup_completed", "Follow-up Completed"),
                            ("imported", "Imported"),
                            ("score_update", "Score Updated"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leads.lead",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_activities",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Activity",
                "verbose_name_plural": "Lead Activities",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LeadImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="lead_imports/")),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "column_mapping",
                    models.JSONField(
                        default=dict,
                        help_text='e.g. {"A": "name", "B": "phone", "C": "city"}',
                    ),
                ),
                (
                    "duplicate_action",
                    models.CharField(
                        choices=[
                            ("skip", "Skip duplicates"),
                            ("update", "Update existing"),
                            ("create_new", "Create new (allow duplicates)"),
                        ],
                        default="skip",
                        max_length=20,
                    ),
                ),
                (
                    "default_source",
                    models.CharField(
                        choices=[
                            ("indiamart", "IndiaMART"),
                            ("meta_facebook", "Meta - Facebook Lead Ads"),
                            ("meta_instagram", "Meta - Instagram Lead Ads"),
                            ("99acres", "99acres"),
                            ("housing_com", "Housing.com"),
                            ("magicbricks", "MagicBricks"),
                            ("justdial", "JustDial"),
                            ("sulekha", "Sulekha"),
                            ("tradeindia", "TradeIndia"),
                            ("google_ads", "Google Ads Lead Forms"),
                            ("website", "Website Widget"),
                            ("webhook", "Webhook"),
                            ("manual", "Manual Entry"),
                            ("csv_import", "CSV Import"),
                            ("api", "API"),
                            ("whatsapp", "WhatsApp Inbound"),
                            ("referral", "Referral"),
                        ],
                        default="manual",
                        max_length=50,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("successful_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("duplicate_rows", models.PositiveIntegerField(default=0)),
                ("row_errors", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "celery_task_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "default_assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_import_assignments",
                        to="authentication.agent",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_jobs",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Import Job",
                "verbose_name_plural": "Lead Import Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="import_job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.leadimportjob",
            ),
        ),
        migrations.CreateModel(
            name="LeadNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="lead_attachments/"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_notes",
                        to="authentication.agent",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Note",
                "verbose_name_plural": "Lead Notes",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "followup_type",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("site_visit", "Site Visit"),
                            ("meeting", "Meeting"),
                            ("demo", "Demo"),
                            ("other", "Other"),
                        ],
                        default="call",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(db_index=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("completion_notes", models.TextField(blank=True, default="")),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="authentication.agent",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followups",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow-up",
                "verbose_name_plural": "Follow-ups",
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(
                        fields=["scheduled_at", "is_completed", "assigned_to"],
                        name="leads_follo_schedul_162621_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, default="")),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="leads.customfield",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_field_values",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom Field Value",
                "unique_together": {("lead", "field")},
            },
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["status", "assigned_to"], name="leads_lead_status_a53442_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["source", "created_at"], name="leads_lead_source_ebb051_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["next_followup_at", "assigned_to"],
                name="leads_lead_next_fo_31d628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["phone"], name="leads_lead_phone_709d42_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["is_deleted", "status"], name="leads_lead_is_dele_461ebd_idx"
            ),
        ),
    ]
