# Generated by Django 5.1.4 on 2026-06-04 06:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallQueueMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Call Queue Membership",
                "verbose_name_plural": "Call Queue Memberships",
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="has_been_worked",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True once the lead has been dialed/dispositioned at least once. A worked lead is never treated as a new lead again.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_dialed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Last time this lead was dialed from a queue (redial cooldown).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lock_expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When the queue lock auto-expires and the lead becomes available to pull again.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Agent who currently has this lead checked out from a queue. Prevents another agent from pulling the same lead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_leads",
                to="authentication.agent",
            ),
        ),
        migrations.CreateModel(
            name="CallQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "filter_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Lead statuses this queue serves, e.g. ["new", "contacted"].',
                    ),
                ),
                (
                    "filter_priorities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Priorities to include, e.g. ["hot", "warm"].',
                    ),
                ),
                (
                    "filter_sources",
                    models.JSONField(
                        blank=True, default=list, help_text="Lead sources to include."
                    ),
                ),
                (
                    "filter_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Only leads having ANY of these tags.",
                    ),
                ),
                (
                    "only_unworked",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only serve leads that have never been worked (fresh leads). Guarantees worked leads are never repeated as new.",
                    ),
                ),
                (
                    "only_followup_due",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only serve leads whose follow-up is due/overdue.",
                    ),
                ),
                (
                    "exclude_dnd",
                    models.BooleanField(
                        default=True, help_text="Skip leads on the TRAI DND registry."
                    ),
                ),
                (
                    "order_by",
                    models.CharField(
                        choices=[
                            ("priority", "Highest priority first"),
                            ("oldest", "Oldest leads first"),
                            ("newest", "Newest leads first"),
                            ("score", "Highest score first"),
                            ("followup_due", "Follow-up due first"),
                        ],
                        default="priority",
                        max_length=20,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual pull"),
                            ("auto", "Auto / power-dialer"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "redial_cooldown_hours",
                    models.PositiveIntegerField(
                        default=24,
                        help_text="A lead dialed from a queue won't be served again until this many hours have passed.",
                    ),
                ),
                (
                    "lock_ttl_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How long a pulled lead stays locked to an agent before it auto-releases back to the queue.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_queues",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Queue",
                "verbose_name_plural": "Call Queues",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="locked_queue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_leads",
                to="leads.callqueue",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["assigned_to", "has_been_worked", "status"],
                name="leads_lead_assigne_6a86cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["lock_expires_at"], name="leads_lead_lock_ex_d5050b_idx"
            ),
        ),
        migrations.AddField(
            model_name="callqueuemembership",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_memberships",
                to="authentication.agent",
            ),
        ),
        migrations.AddField(
            model_name="callqueuemembership",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="leads.callqueue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="callqueuemembership",
            unique_together={("queue", "agent")},
        ),
    ]
