# Generated by Django 5.1.4 on 2026-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_callqueuemembership_lead_has_been_worked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="ad_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific ad / ad set name within the campaign.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="campaign_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Ad campaign name the lead came from (e.g. Meta/Google campaign).",
                max_length=300,
            ),
        ),
    ]
