# Generated by Django 5.1.4 on 2026-09-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_lead_ad_name_lead_campaign_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(
                choices=[
                    ("indiamart", "IndiaMART"),
                    ("meta_facebook", "Meta - Facebook Lead Ads"),
                    ("meta_instagram", "Meta - Instagram Lead Ads"),
                    ("meta_ctwa", "Meta - Click to WhatsApp"),
                    ("99acres", "99acres"),
                    ("housing_com", "Housing.com"),
                    ("magicbricks", "MagicBricks"),
                    ("justdial", "JustDial"),
                    ("sulekha", "Sulekha"),
                    ("tradeindia", "TradeIndia"),
                    ("google_ads", "Google Ads Lead Forms"),
                    ("website", "Website Widget"),
                    ("webhook", "Webhook"),
                    ("manual", "Manual Entry"),
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                    ("whatsapp", "WhatsApp Inbound"),
                    ("referral", "Referral"),
                ],
                db_index=True,
                default="manual",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leadimportjob",
            name="default_source",
            field=models.CharField(
                choices=[
                    ("indiamart", "IndiaMART"),
                    ("meta_facebook", "Meta - Facebook Lead Ads"),
                    ("meta_instagram", "Meta - Instagram Lead Ads"),
                    ("meta_ctwa", "Meta - Click to WhatsApp"),
                    ("99acres", "99acres"),
                    ("housing_com", "Housing.com"),
                    ("magicbricks", "MagicBricks"),
                    ("justdial", "JustDial"),
                    ("sulekha", "Sulekha"),
                    ("tradeindia", "TradeIndia"),
                    ("google_ads", "Google Ads Lead Forms"),
                    ("website", "Website Widget"),
                    ("webhook", "Webhook"),
                    ("manual", "Manual Entry"),
                    ("csv_import", "CSV Import"),
                    ("api", "API"),
                    ("whatsapp", "WhatsApp Inbound"),
                    ("referral", "Referral"),
                ],
                default="manual",
                max_length=50,
            ),
        ),
    ]
