# Generated by Django 5.1.4 on 2026-09-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_notification'),
        ('leads', '0004_alter_lead_source_alter_leadimportjob_default_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadimportjob',
            name='assign_max_per_agent',
            field=models.PositiveIntegerField(blank=True, help_text="Optional ceiling on an agent's TOTAL open leads. Null = no cap.", null=True),
        ),
        migrations.AddField(
            model_name='leadimportjob',
            name='assign_method',
            field=models.CharField(default='round_robin', help_text='round_robin | equal_split | least_loaded — see services/distribution.py.', max_length=20),
        ),
        migrations.AddField(
            model_name='leadimportjob',
            name='assign_to_agents',
            field=models.JSONField(blank=True, default=list, help_text='Agent ids to distribute across. Order is respected by round robin.'),
        ),
        migrations.AddField(
            model_name='leadimportjob',
            name='assignment_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='leadimportjob',
            name='auto_assign',
            field=models.BooleanField(default=False, help_text='Distribute the imported leads across agents when the import finishes.'),
        ),
        migrations.AddField(
            model_name='leadimportjob',
            name='batch_name',
            field=models.CharField(blank=True, default='', help_text="Label for this import's batch. Blank → 'Batch <n>'.", max_length=150),
        ),
        migrations.CreateModel(
            name='LeadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(db_index=True, help_text="Per-tenant running batch number. Shown to admins as 'Batch 7'.", unique=True)),
                ('name', models.CharField(blank=True, default='', help_text='Admin-chosen label. Falls back to a generated one — see `label`.', max_length=150)),
                ('kind', models.CharField(choices=[('import', 'File import'), ('webhook', 'Webhook / API'), ('manual', 'Manually created')], default='import', max_length=15)),
                ('source', models.CharField(choices=[('indiamart', 'IndiaMART'), ('meta_facebook', 'Meta - Facebook Lead Ads'), ('meta_instagram', 'Meta - Instagram Lead Ads'), ('meta_ctwa', 'Meta - Click to WhatsApp'), ('99acres', '99acres'), ('housing_com', 'Housing.com'), ('magicbricks', 'MagicBricks'), ('justdial', 'JustDial'), ('sulekha', 'Sulekha'), ('tradeindia', 'TradeIndia'), ('google_ads', 'Google Ads Lead Forms'), ('website', 'Website Widget'), ('webhook', 'Webhook'), ('manual', 'Manual Entry'), ('csv_import', 'CSV Import'), ('api', 'API'), ('whatsapp', 'WhatsApp Inbound'), ('referral', 'Referral')], db_index=True, default='csv_import', max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open — still receiving leads'), ('closed', 'Closed')], db_index=True, default='open', max_length=10)),
                ('collection_date', models.DateField(blank=True, db_index=True, null=True)),
                ('total_leads', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_batches', to='authentication.agent')),
                ('import_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch', to='leads.leadimportjob')),
            ],
            options={
                'verbose_name': 'Lead Batch',
                'verbose_name_plural': 'Lead Batches',
                'ordering': ['-number'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadbatch'),
        ),
        migrations.AddIndex(
            model_name='leadbatch',
            index=models.Index(fields=['source', 'collection_date'], name='lead_batch_src_date_idx'),
        ),
        migrations.AddIndex(
            model_name='leadbatch',
            index=models.Index(fields=['status', '-number'], name='lead_batch_status_num_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'webhook')), fields=('source', 'collection_date'), name='uniq_webhook_batch_per_source_day'),
        ),
    ]
