# Generated by Django 5.1.4 on 2026-09-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_batches_and_auto_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadbatch',
            name='number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text="Per-tenant running batch number, shown to admins as 'Batch 7'. Seeded from the row's own pk so it is monotonic and never reused. Null only for the instant between INSERT and that update.", null=True, unique=True),
        ),
    ]
