# Generated by Django 5.1.4 on 2026-10-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_repair_next_followup_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="is_auto",
            field=models.BooleanField(default=False),
        ),
    ]
