# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(db_index=True, max_length=200)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("real_estate", "Real Estate"),
                            ("edtech", "EdTech / Online Education"),
                            ("bfsi", "Banking, Financial Services & Insurance (BFSI)"),
                            ("insurance", "Insurance"),
                            ("automobile", "Automobile / Auto Dealership"),
                            ("manufacturing", "Manufacturing / B2B"),
                            ("it_services", "IT Services / SaaS"),
                            ("healthcare", "Healthcare"),
                            ("ecommerce", "E-Commerce / D2C"),
                            ("staffing", "Staffing / Recruitment"),
                            ("retail", "Retail"),
                            ("hospitality", "Hospitality / Travel"),
                            ("education", "Education / Institute"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="GST Identification Number (15 chars). Optional.",
                        max_length=15,
                    ),
                ),
                ("billing_address", models.TextField(blank=True, default="")),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="2-letter Indian state code for GST (e.g., MH, DL, KA).",
                        max_length=2,
                    ),
                ),
                ("pincode", models.CharField(blank=True, default="", max_length=6)),
                ("primary_contact_name", models.CharField(max_length=150)),
                (
                    "primary_contact_email",
                    models.EmailField(db_index=True, max_length=254),
                ),
                (
                    "primary_contact_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+91[6-9]\\d{9}$",
                                "Enter a valid Indian mobile number (+91XXXXXXXXXX).",
                            )
                        ],
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master kill-switch. Set to False to block all logins.",
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                (
                    "onboarding_step",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Current onboarding step (1–5)."
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tenant_logos/"),
                ),
                (
                    "primary_color",
                    models.CharField(
                        default="#4F46E5",
                        help_text="Hex color code for brand primary color.",
                        max_length=7,
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom domain for white-label tenants (e.g., crm.acmerealty.in).",
                        max_length=253,
                    ),
                ),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes visible only to TeleCRM super admins.",
                    ),
                ),
                ("total_agents", models.PositiveIntegerField(default=0)),
                ("total_leads", models.PositiveIntegerField(default=0)),
                ("total_calls_today", models.PositiveIntegerField(default=0)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenants",
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
            },
        ),
    ]
