# Generated by Django 5.1.4 on 2026-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="max_agents_override",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Cap on ACTIVE agents for this tenant only. Leave blank to use the plan's limit. Set it to sell extra seats without moving the tenant to a bigger plan, or to hold one below their plan's allowance. 0 blocks any new agent.",
                null=True,
                verbose_name="Agent seat cap (override)",
            ),
        ),
    ]
