# Generated by Django 5.1.4 on 2026-09-27 07:30

from django.db import migrations, models


def classify_existing_suspensions(apps, schema_editor):
    """
    Tenants already suspended get a kind from their suspension notes: the
    trial task writes "Trial period expired", which a payment may lift. Any
    other suspension is treated as the super admin's, which it may not — the
    safe side when the reason is unknown.
    """
    Tenant = apps.get_model("tenants", "Tenant")
    for tenant in Tenant.objects.filter(is_active=False):
        notes = tenant.internal_notes or ""
        last = notes[notes.rfind("[SUSPENDED"):] if "[SUSPENDED" in notes else ""
        tenant.suspension_kind = "billing" if "Trial period expired" in last else "admin"
        tenant.save(update_fields=["suspension_kind"])


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_max_agents_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="suspension_kind",
            field=models.CharField(
                blank=True,
                choices=[("billing", "Billing"), ("admin", "Super admin")],
                default="",
                help_text="Set by suspend(); cleared by activate().",
                max_length=10,
            ),
        ),
        migrations.RunPython(classify_existing_suspensions, migrations.RunPython.noop),
    ]
