# Generated by Django 5.1.4 on 2026-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenant_suspension_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="lead_form_settings",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
