# Generated by Django 5.1.4 on 2026-10-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_lead_form_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='agent_web_access',
            field=models.BooleanField(default=True, verbose_name='Agents may sign in on the web'),
        ),
    ]
