# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.core.validators
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("invoice_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pre-tax amount.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hsn_sac_code",
                    models.CharField(
                        default="998315", help_text="SAC code for SaaS.", max_length=10
                    ),
                ),
                ("is_interstate", models.BooleanField(default=False)),
                (
                    "customer_gstin",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "customer_state",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "billing_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("billing_address_snapshot", models.TextField(blank=True, default="")),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("billing_period_start", models.DateField(blank=True, null=True)),
                ("billing_period_end", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invoice_pdf",
                    models.FileField(
                        blank=True,
                        help_text="Generated PDF invoice.",
                        null=True,
                        upload_to="invoices/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                            ("custom", "Custom"),
                        ],
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly price in INR (pre-GST).",
                        max_digits=10,
                    ),
                ),
                (
                    "price_yearly",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Yearly price in INR (pre-GST). Usually ~20% discount.",
                        max_digits=10,
                    ),
                ),
                (
                    "razorpay_monthly_plan_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "razorpay_yearly_plan_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "max_agents",
                    models.PositiveIntegerField(
                        default=5, help_text="Max number of agents allowed."
                    ),
                ),
                (
                    "max_leads",
                    models.PositiveIntegerField(
                        default=5000, help_text="Max total leads stored."
                    ),
                ),
                (
                    "max_leads_per_day",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Max new leads per day (from all sources).",
                    ),
                ),
                (
                    "max_whatsapp_bulk_per_day",
                    models.PositiveIntegerField(
                        default=0, help_text="Max WhatsApp bulk messages per day."
                    ),
                ),
                (
                    "max_email_bulk_per_day",
                    models.PositiveIntegerField(
                        default=0, help_text="Max bulk emails per day."
                    ),
                ),
                (
                    "max_sms_per_day",
                    models.PositiveIntegerField(
                        default=0, help_text="Max SMS per day."
                    ),
                ),
                (
                    "storage_gb",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Storage limit in GB (call recordings, attachments).",
                    ),
                ),
                (
                    "custom_fields_limit",
                    models.PositiveIntegerField(
                        default=10, help_text="Max custom CRM fields allowed."
                    ),
                ),
                (
                    "lead_sources_limit",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Max lead source integrations enabled simultaneously.",
                    ),
                ),
                (
                    "whatsapp_templates_limit",
                    models.PositiveIntegerField(
                        default=5, help_text="Max saved WhatsApp message templates."
                    ),
                ),
                (
                    "data_retention_days",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Days to retain lead/call data before archiving.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Inactive plans cannot be selected.",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Show on public pricing page. Enterprise plans are typically private.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(
                        choices=[
                            ("indiamart", "IndiaMART Integration"),
                            ("meta_lead_ads", "Meta (Facebook/Instagram) Lead Ads"),
                            ("99acres", "99acres Integration"),
                            ("housing_com", "Housing.com Integration"),
                            ("magicbricks", "MagicBricks Integration"),
                            ("justdial", "JustDial Integration"),
                            ("sulekha", "Sulekha Integration"),
                            ("tradeindia", "TradeIndia Integration"),
                            ("google_ads_leads", "Google Ads Lead Forms"),
                            ("website_widget", "Website Lead Widget"),
                            ("generic_webhook", "Generic Inbound Webhook"),
                            (
                                "outbound_webhook",
                                "Outbound Webhook (push to external CRM)",
                            ),
                            ("zapier_integration", "Zapier / Make.com Integration"),
                            ("whatsapp_single", "WhatsApp Business (Single Provider)"),
                            (
                                "whatsapp_multi",
                                "WhatsApp Business (Multiple Providers)",
                            ),
                            ("bulk_whatsapp", "Bulk WhatsApp Campaigns"),
                            ("bulk_email", "Bulk Email Campaigns"),
                            ("bulk_sms", "Bulk SMS Campaigns"),
                            ("one_click_whatsapp", "One-Click WhatsApp"),
                            ("one_click_email", "One-Click Email"),
                            ("one_click_sms", "One-Click SMS"),
                            ("email_campaigns", "Email Campaign Management"),
                            ("sms_campaigns", "SMS Campaign Management"),
                            ("whatsapp_incoming", "Incoming WhatsApp Messages"),
                            ("call_recording_access", "Call Recording Access (Play)"),
                            ("call_recording_download", "Call Recording Download"),
                            ("cloud_telephony", "Cloud Telephony (Exotel/Knowlarity)"),
                            ("auto_dialer", "Auto-Dialer (Mobile App)"),
                            ("custom_fields", "Custom CRM Fields"),
                            ("lead_scoring", "Lead Scoring"),
                            ("lead_pipeline", "Lead Pipeline / Funnel View"),
                            ("lead_import", "Lead Import (CSV/Excel)"),
                            ("lead_export", "Lead Export (CSV/Excel)"),
                            ("followup_automation", "Follow-up Automation Rules"),
                            ("contact_history", "Full Contact History"),
                            ("team_management", "Team Management"),
                            ("agent_monitoring", "Real-time Agent Monitoring"),
                            ("agent_gps_tracking", "Agent GPS Tracking"),
                            ("agent_performance", "Agent Performance Reports"),
                            ("basic_reports", "Basic Reports"),
                            ("advanced_reports", "Advanced Analytics & Reports"),
                            ("scheduled_reports", "Scheduled Email Reports"),
                            ("custom_dashboards", "Custom Dashboards"),
                            ("api_access", "REST API Access"),
                            ("white_label", "White-label Branding"),
                            ("priority_support", "Priority Support"),
                        ],
                        help_text="Feature identifier from FeatureKey constants.",
                        max_length=100,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plan Feature",
                "verbose_name_plural": "Plan Features",
                "ordering": ["feature_key"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "razorpay_subscription_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "razorpay_customer_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                            ("suspended", "Suspended"),
                        ],
                        db_index=True,
                        default="trial",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("trial_end", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
            },
        ),
    ]
