# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.TextField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "updated_by",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
            ],
            options={
                "verbose_name": "Global Setting",
                "verbose_name_plural": "Global Settings",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("tenant_admin", "Tenant Admin"),
                            ("agent", "Agent"),
                            ("system", "System (Celery)"),
                            ("api", "API"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="PK of the actor (user ID, agent ID, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("actor_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "actor_user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "tenant_schema",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Schema name if action was in a tenant context. Empty for public.",
                        max_length=100,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("login_failed", "Login Failed"),
                            ("impersonate", "Impersonate"),
                            ("plan_change", "Plan Change"),
                            ("suspend", "Suspend"),
                            ("activate", "Activate"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("bulk_action", "Bulk Action"),
                            ("settings_change", "Settings Change"),
                            ("password_change", "Password Change"),
                            ("password_reset", "Password Reset"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model name: 'Tenant', 'Agent', 'Lead', etc.",
                        max_length=100,
                    ),
                ),
                ("entity_id", models.CharField(blank=True, default="", max_length=100)),
                (
                    "entity_repr",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable description of the affected entity.",
                        max_length=300,
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dict with 'before' and 'after' states for update actions.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-text description of what happened.",
                    ),
                ),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this log entry involves sensitive data (e.g., passwords).",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["tenant_schema", "timestamp"],
                        name="superadmin__tenant__3fa19d_idx",
                    ),
                    models.Index(
                        fields=["actor_email", "timestamp"],
                        name="superadmin__actor_e_88a786_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="superadmin__action_ee6d9b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
                (
                    "created_by",
                    models.EmailField(
                        help_text="Super admin who wrote this note.", max_length=254
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Pin important notes to the top."
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_notes",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Note",
                "verbose_name_plural": "Support Notes",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
    ]
