# Generated by Django 5.1.4 on 2026-05-30 12:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallDisposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                (
                    "is_positive",
                    models.BooleanField(
                        default=False,
                        help_text="True for positive outcomes (Connected, Interested, etc.)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "auto_followup_hours",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="If set, auto-schedule a follow-up this many hours after call.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Disposition",
                "verbose_name_plural": "Call Dispositions",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CallLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("outbound", "Outbound"),
                            ("inbound", "Inbound"),
                            ("missed", "Missed"),
                        ],
                        db_index=True,
                        default="outbound",
                        max_length=10,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="The external number dialled/received.", max_length=15
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "is_connected",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True if the call was actually answered.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("exotel", "Exotel"),
                            ("mcube", "MCUBE"),
                            ("knowlarity", "Knowlarity"),
                            ("ozonetel", "Ozonetel"),
                            ("manual", "Manual Entry"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "provider_call_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Call SID / ID from the telecom provider.",
                        max_length=200,
                    ),
                ),
                (
                    "provider_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw webhook payload from the provider.",
                    ),
                ),
                (
                    "call_cost_paise",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Call cost in Indian paise (1 rupee = 100 paise). Set by provider webhook.",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="authentication.agent",
                    ),
                ),
                (
                    "disposition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="calls.calldisposition",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated lead. Null for calls not linked to a lead.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Log",
                "verbose_name_plural": "Call Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CallRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Stored in S3 with private access.",
                        upload_to="call_recordings/%Y/%m/",
                    ),
                ),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("mp3", "MP3"),
                            ("wav", "WAV"),
                            ("ogg", "OGG"),
                            ("m4a", "M4A"),
                        ],
                        default="mp3",
                        max_length=10,
                    ),
                ),
                ("transcript", models.TextField(blank=True, default="")),
                (
                    "transcript_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="calls.calllog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Recording",
                "verbose_name_plural": "Call Recordings",
            },
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["agent", "started_at"], name="calls_calll_agent_i_b755b6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["lead", "started_at"], name="calls_calll_lead_id_0af421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["started_at", "direction"],
                name="calls_calll_started_52c5a0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="calllog",
            index=models.Index(
                fields=["is_connected", "started_at"],
                name="calls_calll_is_conn_83231c_idx",
            ),
        ),
    ]
