# Generated by Django 5.1.4 on 2026-06-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrecording",
            name="cloud_public_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cloudinary public_id (for deletion / re-upload).",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="cloud_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Cloudinary secure URL of the recording audio.",
                max_length=600,
            ),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="matched_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("filename_number", "Phone number in filename"),
                    ("timestamp", "Timestamp + duration window"),
                    ("manual", "Manual upload"),
                ],
                default="",
                help_text="How the device file was matched to this call.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="source_filename",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Original filename of the OEM call-recording file on the device.",
                max_length=400,
            ),
        ),
        migrations.AlterField(
            model_name="callrecording",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Optional local/S3 copy. Primary storage is Cloudinary (cloud_url).",
                null=True,
                upload_to="call_recordings/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="callrecording",
            name="format",
            field=models.CharField(
                choices=[
                    ("mp3", "MP3"),
                    ("wav", "WAV"),
                    ("ogg", "OGG"),
                    ("m4a", "M4A"),
                    ("amr", "AMR"),
                ],
                default="mp3",
                max_length=10,
            ),
        ),
    ]
