# Generated by Django 6.0.6 on 2026-07-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0002_callrecording_cloud_public_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="callrecording",
            name="transcribed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="transcript_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="transcript_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Language auto-detected by the speech-to-text provider.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="callrecording",
            name="transcript_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Speech-to-text model that produced the transcript.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="callrecording",
            name="transcript_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
