# Generated by Django 5.1.4 on 2026-10-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calls", "0003_callrecording_transcribed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calldisposition",
            name="lead_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new", "New"),
                    ("attempted", "Attempted"),
                    ("contacted", "Contacted"),
                    ("interested", "Interested"),
                    ("not_interested", "Not Interested"),
                    ("follow_up", "Follow-up Scheduled"),
                    ("negotiation", "In Negotiation"),
                    ("converted", "Converted / Won"),
                    ("lost", "Lost"),
                    ("duplicate", "Duplicate"),
                ],
                default="",
                help_text="Move the lead to this status when a call is saved with this outcome. Blank = leave it.",
                max_length=20,
            ),
        ),
    ]
