# Generated by Django 6.0.6 on 2026-07-10 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calls", "0003_callrecording_transcribed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CallInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Two or three sentences on what was discussed and agreed.",
                    ),
                ),
                (
                    "sentiment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("positive", "Positive"),
                            ("neutral", "Neutral"),
                            ("negative", "Negative"),
                        ],
                        db_index=True,
                        default="",
                        help_text="The lead's disposition towards the offer, not the agent's tone.",
                        max_length=10,
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        blank=True,
                        help_text="-1.0 (hostile) to 1.0 (enthusiastic).",
                        null=True,
                    ),
                ),
                (
                    "key_points",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of strings: the facts worth carrying into the next call.",
                    ),
                ),
                (
                    "objections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of strings: reasons the lead gave for not buying.",
                    ),
                ),
                (
                    "next_action",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The single most useful thing the agent should do next.",
                    ),
                ),
                (
                    "coaching_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Feedback for the agent — what to do differently next time.",
                    ),
                ),
                ("model", models.CharField(blank=True, default="", max_length=60)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                (
                    "generated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "call",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight",
                        to="calls.calllog",
                    ),
                ),
                (
                    "suggested_disposition",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only ever one of the tenant's own active dispositions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_suggestions",
                        to="calls.calldisposition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Insight",
                "verbose_name_plural": "Call Insights",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["sentiment", "generated_at"],
                        name="ai_callinsi_sentime_3873cb_idx",
                    ),
                    models.Index(
                        fields=["status", "generated_at"],
                        name="ai_callinsi_status_c9de11_idx",
                    ),
                ],
            },
        ),
    ]
