# Generated by Django 5.1.4 on 2026-10-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callinsight",
            options={
                "ordering": ["-generated_at"],
                "verbose_name": "AI Call Summary",
                "verbose_name_plural": "AI Call Summaries",
            },
        ),
    ]
