# Generated by Django 5.1.4 on 2026-05-30 12:23

import apps.core.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Login email. Must be unique within this tenant.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+91[6-9]\\d{9}$",
                                "Enter a valid Indian mobile number (+91XXXXXXXXXX).",
                            )
                        ],
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Company employee ID (optional, for internal reference).",
                        max_length=50,
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.storage.get_profile_photo_upload_path,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Tenant Admin"),
                            ("manager", "Manager"),
                            ("senior_agent", "Senior Agent"),
                            ("agent", "Agent"),
                            ("readonly", "Read Only"),
                        ],
                        db_index=True,
                        default="agent",
                        max_length=20,
                    ),
                ),
                (
                    "is_tenant_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Designates this agent as the primary tenant administrator.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Deactivate to block login without deleting the agent.",
                    ),
                ),
                (
                    "must_change_password",
                    models.BooleanField(
                        default=False,
                        help_text="Force password change on next login (set on account creation).",
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("en", "English"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "shift_start",
                    models.TimeField(
                        blank=True,
                        help_text="Shift start time (for availability display in monitoring).",
                        null=True,
                    ),
                ),
                (
                    "shift_end",
                    models.TimeField(
                        blank=True, help_text="Shift end time.", null=True
                    ),
                ),
                (
                    "working_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of working day numbers: 0=Mon, 1=Tue, ..., 6=Sun. E.g., [0,1,2,3,4] for Monday–Friday.",
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Firebase Cloud Messaging token for push notifications.",
                    ),
                ),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("total_login_count", models.PositiveIntegerField(default=0)),
                (
                    "last_active_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the agent made an API request.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent",
                "verbose_name_plural": "Agents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Team",
                "verbose_name_plural": "Teams",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentLoginSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("login_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile App"),
                            ("web", "Web Browser"),
                            ("api", "API"),
                        ],
                        default="mobile",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Active session (not yet logged out).",
                    ),
                ),
                (
                    "jwt_jti",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_sessions",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login Session",
                "verbose_name_plural": "Login Sessions",
                "ordering": ["-login_time"],
            },
        ),
        migrations.CreateModel(
            name="AgentTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_team_lead",
                    models.BooleanField(
                        default=False,
                        help_text="Team leads can view their team members' leads.",
                    ),
                ),
                ("joined_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="authentication.agent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="authentication.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Team Membership",
                "verbose_name_plural": "Agent Team Memberships",
                "unique_together": {("agent", "team")},
            },
        ),
    ]
