# Generated by Django 5.1.4 on 2026-09-09 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_agent_role_back_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("followup_scheduled", "Follow-up scheduled"),
                            ("followup_due", "Follow-up due"),
                            ("followup_overdue", "Follow-up overdue"),
                            ("lead_assigned", "Lead assigned"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        default="system",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "lead_id_ref",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="leads.Lead id this concerns, if any.",
                        null=True,
                    ),
                ),
                (
                    "followup_id_ref",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="leads.FollowUp id this concerns, if any.",
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Client route to open, e.g. /leads/42.",
                        max_length=200,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="authentication.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notif_recipient_unread_idx",
                    )
                ],
            },
        ),
    ]
