# Generated by Django 5.1.4 on 2026-10-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_owner_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('admin', 'Tenant Admin'), ('manager', 'Manager'), ('hr', 'HR'), ('accounts', 'Accounts'), ('recruiter', 'Recruiter'), ('senior_agent', 'Senior Agent'), ('agent', 'Agent'), ('readonly', 'Read Only')], db_index=True, default='agent', max_length=20),
        ),
    ]
